#ifndef GAME_LOCALIZATION_ENTITY_ZH_H
#define GAME_LOCALIZATION_ENTITY_ZH_H

struct SEntityTranslationEntry
{
	const char *m_pOrg;
	const char *m_pZh;
};

static const SEntityTranslationEntry s_aEntityTranslationsZh[] = {
	{" seconds", " 秒"},
	{" seconds (never)", " 秒 (永不)"},
	{"\"advanced\" Gores Mode", "“高级” Gores 模式"},
	{"_ or ' ' = Space", "_ 或 ' ' = 空格"},
	{"a = Angle", "a = 瞄准角度 (Angle)"},
	{"Add Action", "添加动作"},
	{"Add Bind", "添加按键绑定"},
	{"Add Entry", "添加条目"},
	{"Add Group", "添加分组"},
	{"Add Item", "添加项目"},
	{"Adjust your prediction margin while frozen", "处于冰冻状态时调整预测边距"},
	{"After Load", "加载后"},
	{"Allow Duplicate Entries", "允许重复条目"},
	{"Alpha", "透明度"},
	{"Amount", "数量/数值"},
	{"Anti Latency Tools", "防延迟工具"},
	{"Anti Ping Smoothing", "防 Ping 平滑"},
	{"Anti Spawn Block", "防止出生点卡人"},
	{"Apply", "应用"},
	{"Are you sure that you want to remove '%s' from your war groups?", "确定要从对手/战争分组中移除 '%s' 吗？"},
	{"Auto Add to Warlist on Name Change", "改名时自动添加到对手/敌人列表"},
	{"Auto Enable if Gametype is \"Gores\"", "在 Gores 模式服务器中自动开启"},
	{"Automation", "自动化"},
	{"Background Draw", "后台渲染/绘制"},
	{"Bind Wheel Key:", "绑定轮盘按键："},
	{"Bindwheel", "快捷绑定轮盘"},
	{"Black", "黑色"},
	{"Bottom", "底部"},
	{"Button name", "按钮名称"},
	{"c = Position", "c = 坐标位置 (Position)"},
	{"Center", "居中"},
	{"Change indicator offset based on distance to other tees", "根据与其他 Tee 的距离调整指示器偏移"},
	{"Chat Bubble Size", "聊天气泡大小"},
	{"Chat Bubbles", "聊天气泡"},
	{"Chat Preview", "聊天预览"},
	{"Chat Settings", "聊天设置"},
	{"Chatbinds", "聊天绑定"},
	{"Clan", "战队"},
	{"Clan: %s", "战队：%s"},
	{"Click to edit an action, drag it to move it somewhere else", "点击编辑动作，拖拽可调整位置"},
	{"Client Id", "客户端 ID"},
	{"Client Prefix", "客户端前缀"},
	{"Color", "颜色"},
	{"Colored frozen tee skins", "冰冻 Tee 皮肤着色"},
	{"Colors", "颜色"},
	{"Colors in chat", "聊天中显示颜色"},
	{"Colors in scoreboard", "计分板中显示颜色"},
	{"Colors in specmenu", "旁观菜单中显示颜色"},
	{"Command", "指令"},
	{"Command, %d is replaced by the client id", "指令，%d 会被替换为客户端 ID"},
	{"Command:", "指令："},
	{"Commands List", "指令列表"},
	{"Config Files", "配置文件"},
	{"Copy Skin From Closest Player Now", "立即复制最近玩家的皮肤"},
	{"Copy to Rcon", "复制到 Rcon"},
	{"Cosmetic Settings", "外观设置"},
	{"Count frozen tees", "统计被冰冻的 Tee 数量"},
	{"Cursor Opacity in Spec", "旁观模式光标不透明度"},
	{"Custom Font:", "自定义字体："},
	{"Custom colors", "自定义颜色"},
	{"d = Prediction", "d = 预测差 (Prediction)"},
	{"DDNet Settings", "DDNet 原版设置"},
	{"Delay", "延迟"},
	{"Delete", "删除"},
	{"Delete Action", "删除动作"},
	{"Deselect All", "取消全选"},
	{"Developers:", "开发者："},
	{"Disable if You Have Any Weapon", "持有重武器时自动暂停"},
	{"Discord RPC", "Discord 状态同步 (RPC)"},
	{"Do Dummy and Main Player at the same time", "主分身和替身同时应用"},
	{"Don't Kill if Moving", "移动时不自杀"},
	{"Don't show moving tiles in entities", "不在实体层显示移动图块"},
	{"Done", "完成"},
	{"Dont Kill if Teammate is in View", "队友在视野中时不自杀"},
	{"Dont predict other players if you are frozen", "自身被冰冻时不预测其他玩家"},
	{"Draw where mouse is", "绘制鼠标位置"},
	{"Dummy", "分身/替身"},
	{"Dummy Hammer Settings", "分身锤击 (Dummy Hammer) 设置"},
	{"E-Client Setting", "Entity 客户端设置"},
	{"Edit", "编辑"},
	{"Edit Entry", "编辑条目"},
	{"Enable Deleting", "启用删除"},
	{"Enable map overview", "启用小地图全景"},
	{"Enable media island", "启用媒体灵动岛"},
	{"Enable Serverside Rainbow", "启用服务器端彩虹"},
	{"Enable tee trails", "启用 Tee 轨迹拖尾"},
	{"Enable warlist", "启用对手/敌人列表 (Warlist)"},
	{"entries", "个条目"},
	{"Execute before connect", "连接前执行控制台指令"},
	{"Execute Command", "执行指令"},
	{"Execute on join", "加入时执行控制台指令"},
	{"Explored area opacity", "已探索区域不透明度"},
	{"Extensions", "扩展"},
	{"Extra tick other tees (increases other tees latency, \nmakes dragging slightly easier when using fast input)", "对其他 Tee 额外增加 Tick（增加其他玩家延迟，\n在使用快速输入时拖拽稍微更顺手）"},
	{"f = FPS", "f = 帧率 (FPS)"},
	{"fade in for", "淡入耗时"},
	{"fade out for", "淡出耗时"},
	{"Fade trail alpha", "渐隐轨迹透明度"},
	{"Fast Input (reduced visual delay)", "极速输入 (降低视觉延迟)"},
	{"Fire Trail Effect", "火焰轨迹特效"},
	{"Fonts Folder", "字体文件夹"},
	{"Freeze Kill", "冰冻自杀 (Freeze Kill)"},
	{"Freeze stars", "冰冻星星"},
	{"Freeze width", "冰冻线宽度"},
	{"Friend Color in Spectate Menu", "旁观菜单中好友颜色"},
	{"Friend Prefix", "好友前缀"},
	{"Frozen Margin", "冰冻边距"},
	{"Frozen Tee Display", "冰冻 Tee 显示"},
	{"Ghost Tools", "幽灵 (Ghost) 工具"},
	{"Gores Mode", "Gores 自动切枪模式"},
	{"Gores Mode: Disabled", "Gores 模式：已关闭"},
	{"Gores Mode: Enabled", "Gores 模式：已开启"},
	{"Hidden in server browser", "在服务器浏览器中隐藏"},
	{"Hide Enemy Chat (Shows in Console)", "隐藏对手聊天 (转在控制台显示)"},
	{"Hide ghosts of frozen players", "隐藏已冰冻玩家的幽灵"},
	{"Hide indicator for tees on your screen", "隐藏同屏可见玩家的指示器"},
	{"Hide Settings Tabs", "隐藏设置标签页"},
	{"High DDNet Process Priority", "提高 DDNet 客户端进程优先级"},
	{"Hue", "色相"},
	{"Ignore Kill Protection", "忽略自杀保护"},
	{"Indicator alive color", "存活指示器颜色"},
	{"Indicator in freeze color", "冰冻指示器颜色"},
	{"Indicator max distance", "指示器最大距离"},
	{"Indicator max offset", "指示器最大偏移"},
	{"Indicator min offset", "指示器最小偏移"},
	{"Indicator offset", "指示器偏移"},
	{"Indicator opacity", "指示器不透明度"},
	{"Indicator safe color", "安全区指示器颜色"},
	{"Indicator size", "指示器尺寸"},
	{"Info", "信息"},
	{"Input", "输入"},
	{"Invalid command syntax", "无效的指令语法"},
	{"Island color", "灵动岛颜色"},
	{"Island Size", "灵动岛大小"},
	{"Keep Hook Held While Hammering", "分身锤击时保持钩爪抓取 (不松钩)"},
	{"Kill on Freeze", "进冰即自杀"},
	{"Kill width", "自杀线宽度"},
	{"l = Local Time", "l = 本地时间 (Local Time)"},
	{"Left click runs the action on the selection, right click copies it above", "左键对选中项执行动作，右键复制到上方"},
	{"Lht.", "亮度"},
	{"Load", "加载"},
	{"Local Time", "本地时间"},
	{"Lower Discords Process Priority", "降低 Discord 进程优先级"},
	{"Map Overview", "小地图全景概览"},
	{"Max Rows", "最大行数"},
	{"Media Island", "媒体灵动岛"},
	{"Menu Settings", "菜单设置"},
	{"Milliseconds to Wait For", "等待毫秒数"},
	{"Miscellaneous", "杂项设置"},
	{"Moving Tiles:", "移动图块："},
	{"Muted Reply", "被静音时自动回复"},
	{"Name", "名称"},
	{"Name:", "名称："},
	{"Name: %s", "名称：%s"},
	{"New Ball", "生成球"},
	{"New Ball Cursor", "在光标处生成球"},
	{"No", "否"},
	{"No Effect", "无特效"},
	{"No settings match your search", "没有找到匹配的设置"},
	{"No status bar items configured", "未配置任何状态栏项目"},
	{"Notify Message", "提醒通知内容"},
	{"Notify on Join", "玩家加入时发出提醒"},
	{"Notify on Join Name", "关注加入的目标玩家名"},
	{"Notify When Player is Being Moved", "当玩家被移动时发出提醒"},
	{"Notify you everytime someone gets auto added", "每当有人被自动添加时发出提醒"},
	{"Offline Message:", "离线状态消息："},
	{"Online Message:", "在线状态消息："},
	{"Online Players", "在线玩家"},
	{"Only Kill if Fully Frozen", "仅在完全深度冰冻时自杀"},
	{"Only show after joining a team", "仅在加入队伍后显示"},
	{"Only show certain Wartypes in frozen tee display", "在冰冻 Tee 界面中仅显示特定对手/敌人分组"},
	{"Only show map overview while spectating", "仅在旁观模式下显示地图概览"},
	{"Only show outlines in entities", "在实体层中仅显示轮廓线"},
	{"Only Show Team Members in Spectator Mode", "观战/暂停时仅显示同队成员"},
	{"Optimistic prediction in stable direction", "稳定方向的乐观预测"},
	{"Outline freezes & deeps", "高亮冰冻和深冰轮廓"},
	{"Outline kills", "高亮秒杀区轮廓"},
	{"Outline solids", "高亮障碍实体轮廓"},
	{"Outline Teams in Scoreboard", "计分板中高亮队伍轮廓"},
	{"Outline teleporters", "高亮传送门轮廓"},
	{"Outline unfreezes & undeeps", "高亮解冻区轮廓"},
	{"Override", "覆盖"},
	{"Override Entry", "覆盖条目"},
	{"Override Group", "覆盖分组"},
	{"Override Selected", "覆盖所选项"},
	{"Overwrite clan even if empty", "即使为空也覆盖战队名称"},
	{"p = Ping", "p = 延迟 (Ping)"},
	{"Performance", "性能优化"},
	{"Physic Balls", "物理小球"},
	{"Player actions", "玩家动作"},
	{"Player Actions", "玩家快捷动作"},
	{"Player Actions Key:", "玩家动作菜单按键："},
	{"Player Indicator", "玩家方位指示器"},
	{"Player Prefixes in Spectate Menu", "旁观菜单中玩家前缀"},
	{"Predicted alpha", "预测透明度"},
	{"Prediction Margin", "预测边距"},
	{"Profiles", "配置文件配置 (Profiles)"},
	{"Profiles file", "配置文件"},
	{"Pulse", "脉冲呼吸"},
	{"Quick Actions", "快捷动作"},
	{"Quick actions require rcon authentication", "快捷动作需要 RCON 管理员认证"},
	{"r = Race Time", "r = 跑图时间 (Race Time)"},
	{"Rainbow", "彩虹"},
	{"Rainbow Body", "彩虹身体"},
	{"Rainbow Feet", "彩虹脚部"},
	{"Rainbow hook", "彩虹钩爪"},
	{"Rainbow others", "其他玩家彩虹色"},
	{"Rainbow Speed", "彩虹速度"},
	{"Rainbow speed", "彩虹渐变速度"},
	{"Rainbow Tees", "彩虹 Tee 皮肤"},
	{"Rainbow weapons", "彩虹武器"},
	{"Random", "随机"},
	{"Rank", "排名"},
	{"Remember instability for longer", "更持久地记录网络不稳定性"},
	{"Remove Bind", "删除按键绑定"},
	{"Remove Item", "删除项目"},
	{"Remove prediction & antiping in freeze", "冰冻状态下移除预测与防 Ping"},
	{"Remove War Group", "删除对手/敌人分组"},
	{"Render feet as white feet", "将脚部渲染为纯白脚"},
	{"Render ghosts as circles", "将幽灵渲染为圆形"},
	{"Render tiny tees instead of circles", "渲染迷你 Tee 代替圆形"},
	{"Reset position of mouse when opening bindwheel", "打开按键轮盘时重置鼠标位置至中心"},
	{"Reset position of mouse when opening the player actions menu", "打开玩家动作菜单时重置鼠标位置至中心"},
	{"Sat.", "饱和度"},
	{"Save", "保存"},
	{"Save/Load Clan", "保存/加载 战队"},
	{"Save/Load Colors", "保存/加载 颜色"},
	{"Save/Load Emote", "保存/加载 表情"},
	{"Save/Load Flag", "保存/加载 国家旗帜"},
	{"Save/Load Name", "保存/加载 玩家名字"},
	{"Save/Load Skin", "保存/加载 皮肤"},
	{"Select none to show all", "全部不选时显示所有"},
	{"selected", "已选择"},
	{"Server Prefix", "服务器前缀"},
	{"Server-Side Rainbow", "服务器端彩虹效果"},
	{"Settings", "常规设置"},
	{"Show", "显示"},
	{"Show all warlist groups", "显示所有对手/敌人分组"},
	{"Show any enabled Indicators", "显示所有已启用的指示器"},
	{"Show any enabled outlines", "显示所有已启用的轮廓线"},
	{"Show Chat Bubble", "显示头顶聊天气泡"},
	{"Show Chatbubbles above players", "在玩家头顶显示聊天气泡"},
	{"Show clan if war", "是对手/敌人时显示战队"},
	{"Show Client Ids in Chat", "在聊天中显示客户端 ID"},
	{"Show FPS", "显示帧率 (FPS)"},
	{"Show frozen tee display", "显示冰冻 Tee 悬浮信息"},
	{"Show katana on frozen players", "在被冰冻玩家身上显示武士刀"},
	{"Show labels on status bar items", "在状态栏项目上显示文本标签"},
	{"Show Messages of Muted People in The Console", "在控制台中显示被静音玩家的发言"},
	{"Show only freeze Players", "仅显示处于冰冻中的玩家"},
	{"Show other tees' trails", "显示其他玩家的轨迹拖尾"},
	{"Show Ping", "显示延迟 (Ping)"},
	{"Show players without entry", "显示未在名单中的玩家"},
	{"Show seconds on clock", "时钟显示秒数"},
	{"Show Settings Icon When Tee's in a Menu", "玩家打开菜单时显示设置图标"},
	{"Show Snap Rate", "显示快照率 (Snap Rate)"},
	{"Show status bar", "显示底部状态栏"},
	{"Show the Bubbles for", "气泡持续显示时间"},
	{"Show unpredicted ghosts for other players", "为其他玩家显示无预测幽灵"},
	{"Show Visualizer", "显示频谱可视化器"},
	{"Show what it'll look like Server-side", "预览服务器端视角效果"},
	{"Show what Map you're on", "在 Discord 上显示当前所在地图"},
	{"Show when you're the last player", "当你成为最后一名存活玩家时提醒"},
	{"Shown in server browser", "在服务器浏览器中显示"},
	{"Skin Name", "皮肤名称"},
	{"Skin Name:", "皮肤名称："},
	{"Skin Stealer", "皮肤窃取 (Skin Stealer)"},
	{"Skin: %s", "皮肤：%s"},
	{"Solid", "纯色/实体"},
	{"Solid width", "实体线宽度"},
	{"Sort", "排序"},
	{"Sparkle effect", "闪烁微光特效"},
	{"Spec Prefix", "旁观前缀"},
	{"Spectate Settings", "观战与旁观设置"},
	{"Speed", "速度"},
	{"Stats", "统计"},
	{"Status bar", "状态栏"},
	{"Status Bar", "状态栏"},
	{"Status bar alpha", "状态栏不透明度"},
	{"Status Bar Codes:", "状态栏格式代码："},
	{"Status bar color", "状态栏背景颜色"},
	{"Status bar height", "状态栏高度"},
	{"Status Scheme:", "状态栏配色方案："},
	{"Steal Closest Skin Key", "快捷键：窃取最近玩家皮肤"},
	{"Sub-Tick aiming", "Sub-Tick 亚微秒级精准瞄准"},
	{"Suggest Math Results in Chat", "在聊天中提示数学计算结果"},
	{"Swap ghosts and normal players", "互换幽灵与普通玩家显示"},
	{"Swap Reason with Name", "互换原因与名称显示"},
	{"Switch Effect", "切换特效"},
	{"Tabbed reply", "离开窗口/切屏时自动回复"},
	{"Taper trail width", "轨迹尾部锥形渐细"},
	{"Tee", "Tee 角色"},
	{"Tee Size", "Tee 大小"},
	{"Tee trail color", "Tee 轨迹颜色"},
	{"Tee Trails", "Tee 移动轨迹拖尾"},
	{"Tees left alive text", "存活 Tee 剩余文本"},
	{"Tele width", "传送门边框宽度"},
	{"Text alpha", "文本不透明度"},
	{"Text color", "文本颜色"},
	{"Text to Show", "提示文本内容"},
	{"Tile Outlines", "图块边缘轮廓"},
	{"Time until strokes disappear", "线条消失时间"},
	{"To get the Client Id do \"%d\"", "使用 \"%d\" 获取客户端 ID"},
	{"To use the name of the target player do \"%s\"", "使用 \"%s\" 代表目标玩家名称"},
	{"Toggle Dummy Hammer Key", "切换分身锤击按键"},
	{"Toggle ghosts key", "切换幽灵显示按键"},
	{"Toggle Gores mode", "切换 Gores 自动切枪模式"},
	{"Toggle Gores Mode Key", "切换 Gores 模式按键"},
	{"Toggle Keep Hook Key", "切换保持钩爪状态按键"},
	{"Trail alpha", "轨迹透明度"},
	{"Trail length", "轨迹长度"},
	{"Trail width", "轨迹宽度"},
	{"Uncertainty duration", "不确定性持续时间"},
	{"Unfreeze width", "解冻线宽度"},
	{"Unknown rcon command", "未知的 Rcon 管理员指令"},
	{"Unpredicted alpha", "未预测幽灵透明度"},
	{"Use 12 hour clock", "使用 12 小时制"},
	{"Use asset colors and map design for moving tiles in entities", "移动图块在实体层使用素材颜色和地图设计"},
	{"Use Discord Rich Presence", "启用 Discord RPC 丰富状态"},
	{"Use left mouse to select", "鼠标左键：选中"},
	{"Use map design for moving tilesin entities", "实体层移动图块使用地图原生设计"},
	{"Use middle mouse select without copy", "鼠标中键：选中且不复制"},
	{"Use new smoothing algorithm", "使用全新防抖平滑算法"},
	{"Use Old Team Colors", "使用经典队伍颜色"},
	{"Use right mouse to swap with selected", "鼠标右键：与选中项互换位置"},
	{"Use selected asset colors for moving tiles in entities", "实体层移动图块使用选定的素材颜色"},
	{"Use skins instead of ninja tees", "使用玩家原皮肤代替忍者 Tee"},
	{"Use warlist colors instead of regular colors", "使用对手/敌人列表颜色代替常规颜色"},
	{"Use warlist groups for indicator", "指示器采用对手/敌人分组颜色"},
	{"v = Velocity", "v = 移动速度 (Velocity)"},
	{"Visual", "视觉特效"},
	{"Visualizer Alignment:", "音频可视化器对齐方式："},
	{"Visuals", "视觉设置"},
	{"Wait Until Kill", "等待至自杀"},
	{"War Entries", "对手/目标条目"},
	{"War Groups", "对手/目标分组"},
	{"Warlist", "对手/目标列表 (Warlist)"},
	{"Warlist Chat Prefixes", "对手聊天前缀"},
	{"Warlist Prefix", "对手前缀"},
	{"Warlist Prefix Server Info", "对手前缀服务器信息"},
	{"Warlist Sweat Mode", "对手列表专注模式 (Sweat Mode)"},
	{"Width", "宽度"},
	{"Yes", "是"},
	{"Task Scheduler", "定时任务调度器"},
	{"Command:", "执行指令:"},
	{"Interval(ms):", "间隔/延时(ms):"},
	{"Timeout (Once)", "单次延迟 (Timeout)"},
	{"Interval (Loop)", "循环定时 (Interval)"},
	{"Stop All Tasks", "停止所有任务"},
	{"Active Tasks", "运行中的任务数"},
	{"Your profile", "个人档案"},
	{"z = Zoom", "z = 视野缩放 (Zoom)"},
};

#endif // GAME_LOCALIZATION_ENTITY_ZH_H
