# .github/workflows/release.yml
name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for the release (e.g., v1.0.0). Did you remember to bump the version.h?'
        required: true
      release_name:
        description: 'Name of the release'
        required: true
      body:
        description: 'Release description'
        required: false
      run_id:
        description: 'Run ID of the build workflow to download artifacts from'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CLIENT_NAME: E-Client
      TARGET_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: ddnet-ubuntu-22.04
          path: ./artifacts/ubuntu
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.TARGET_REPOSITORY }}
          run-id: ${{ github.event.inputs.run_id }}

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: ddnet-windows-latest
          path: ./artifacts/windows
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.TARGET_REPOSITORY }}
          run-id: ${{ github.event.inputs.run_id }}

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: ddnet-macOS-latest
          path: ./artifacts/macOS
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.TARGET_REPOSITORY }}
          run-id: ${{ github.event.inputs.run_id }}

      - name: Rename and Move Artifacts
        run: |
          mkdir -p ./release-assets
          for file in $(find ./artifacts -type f \( -name "*.zip" -o -name "*.tar.*" -o -name "*.dmg" -o -name "*.apk" \)); do
            echo "Found asset: $file"
            cp "$file" ./release-assets/
          done

      - name: List release assets
        run: |
          echo "Listing ./release-assets directory:"
          ls -la ./release-assets

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.body }}
          fail_on_unmatched_files: false
          files: ./release-assets/*